"""memory_embedding

Revision ID: b9de646ac540
Revises: bab376f3f869
Create Date: 2026-05-19 19:56:53.718820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9de646ac540'
down_revision: Union[str, Sequence[str], None] = 'bab376f3f869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_entries', sa.Column('embedding_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_entries', 'embedding_json')
    # ### end Alembic commands ###
