"""message_status

Revision ID: bab376f3f869
Revises: 775f69b9f899
Create Date: 2026-05-19 14:17:19.824681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab376f3f869'
down_revision: Union[str, Sequence[str], None] = '775f69b9f899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.String(length=20), server_default='done', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
